# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
name: q_gym_env
channels:
    - defaults
    - conda-forge
dependencies:
    - click=8.0.1
    - flake8=3.8.4
    - gensim=4.0.1
    - graphviz=2.40.1
    - lifelines=0.25.11
    - matplotlib=3.4.3
    - nltk=3.6.1
    - notebook
    - numpy=1.21.2
    - pandas=1.2.5
    - pip=21.2.4
    - pygraphviz=1.3
    - python=3.8.3
    - python-dotenv=0.17.1
    - pytest=6.2.5
    - pytorch=1.9.0
    - scikit-learn=0.24.2
    - scipy=1.7.1
    - seaborn=0.10.1
    - setuptools=47.1.1
    - spacy=2.3.5
    - sphinx=4.2.0
    - statsmodels=0.13.0
    - tqdm=4.46.0
    - unidecode=1.2.0
    - pip:
        - -e .